COPY clientes(
  nome_cliente,
  tipo_unidade_abc,
  tipo_unidade,
  contatos,
  ddd_telefone,
  telefone1,
  telefone2,
  cod_unid_neg,
  cod_unid_oper,
  versao_vertis_cliente,
  sql_cliente,
  data_atualizado,
  mormo_aie,
  vacuumbd,
  licencas_cliente,
  ind_certificado_att,
  ind_emite_nfs_api,
  ibt_calculo_correto,
  cliente_municipio,
  antivirus_cliente,
  ind_auditoria,
  ind_sat,
  ind_solic_exam_portal,
  ind_lol,
  ind_loe,
  ind_gerador_pdf,
  ind_portal_novo,
  ind_publ_s3,
  ind_contigencia,
  ind_faturamento_email,
  ind_imagem,
  ind_itf_v,
  ind_itf_m,
  ind_l_aut,
  ind_ftp,
  ind_banco_boleto,
  acesso_cliente_teamviewer,
  senha_acesso_cliente_teamviewer,
  acesso_cliente_anydesk,
  senha_acesso_cliente_anydesk,
  senha_acesso_cliente_hamachi,
  usuario_acesso_cliente,
  senha_acesso_usuario,
  senha_criptografada,
  porta_bd,
  alternativo,
  observacao,
  dth_manutencao_realizada,
  dth_manutencao_futura,
  ind_avisa,
  ind_script,
  executante,
  manutencao_caminho,
  manutencao_armazenamento,
  manutencao_backup,
  manutencao_docdig,
  ip_servidor_cliente,
  so_server,
  postgres_versao,
  email_cliente,
  conta_nuvem_backup,
  senha_conta_nuvem,
  tipo_backup_nuvem,
  pin_google_desktop,
  tamanho_backup,
  senha_smartvertis,
  ind_qrcode,
  ind_nv_server_vrs,
  horario_backups,
  horario_vacuum,
  horarios_reindex,
  ind_sit_confirm,
  indstw
) FROM 'C:/Users/Public/clientesgpi.CSV' DELIMITER ';' CSV HEADER;

DROP TABLE clientes

CREATE TABLE clientes
(
  cod_cliente SERIAL,
  nome_cliente character varying(80),
  tipo_unidade_abc character varying(15),
  tipo_unidade character varying(15),
  contatos character varying(100),
  ddd_telefone bigint,
  telefone1 character varying(50),
  telefone2 character varying(50),
  cod_unid_neg integer,
  cod_unid_oper integer,
  versao_vertis_cliente character varying(15),
  sql_cliente character varying(15),
  data_atualizado character varying(50),
  mormo_aie character varying(15),
  vacuumbd character varying(15),
  licencas_cliente character varying(50),
  ind_certificado_att character varying(15),
  ind_emite_nfs_api character varying(15),
  ibt_calculo_correto character varying(15),
  cliente_municipio character varying(100),
  antivirus_cliente character varying(100),
  ind_auditoria character varying(15),
  ind_sat character varying(50),
  ind_solic_exam_portal character varying(15),
  ind_lol integer,
  ind_loe character varying(25),
  ind_gerador_pdf character varying(25),
  ind_portal_novo character varying(15),
  ind_publ_s3 character varying(15),
  ind_contigencia character varying(15),
  ind_faturamento_email character varying(25),
  ind_imagem character varying(15),
  ind_itf_v character varying(15),
  ind_itf_m character varying(15),
  ind_l_aut character varying(15),
  ind_ftp integer,
  ind_banco_boleto character varying(30),
  acesso_cliente_teamviewer character varying(50),
  senha_acesso_cliente_teamviewer character varying(100),
  acesso_cliente_anydesk character varying(50),
  senha_acesso_cliente_anydesk character varying(100),
  senha_acesso_cliente_hamachi character varying(100),
  usuario_acesso_cliente character varying(100),
  senha_acesso_usuario character varying(100),
  senha_criptografada character varying(100),
  porta_bd character varying(30),
  alternativo character varying(1000),
  observacao character varying(300),
  dth_manutencao_realizada character varying(100),
  dth_manutencao_futura character varying(100),
  ind_avisa character varying(100),
  ind_script character varying(100),
  executante character varying(100),
  manutencao_caminho character varying(300),
  manutencao_armazenamento character varying(300),
  manutencao_backup character varying(100),
  manutencao_docdig character varying(100),
  ip_servidor_cliente character varying(100),
  so_server character varying(100),
  postgres_versao character varying(100),
  email_cliente character varying(200),
  conta_nuvem_backup character varying(150),
  senha_conta_nuvem character varying(100),
  tipo_backup_nuvem character varying(100),
  pin_google_desktop character varying(100),
  tamanho_backup character varying(100),
  senha_smartvertis character varying(100),
  ind_qrcode character varying(15),
  ind_nv_server_vrs character varying(15),
  horario_backups character varying(50),
  horario_vacuum character varying(50),
  horarios_reindex character varying(50),
  ind_sit_confirm character varying(100),
  indstw character varying(50)
)

  